ESLint Config:
  - package/eslint-snowball-config/**

Prettier Config:
  - package/prettier-config/**

Renovate Config:
  - package/renovate-config/**

Semantic Release Config:
  - package/semantic-release-config/**
