/* eslint-disable sort-keys/sort-keys-fix */

module.exports = {
  breaking: {
    description:
      'A change breaking the backward compatibility and/or bringing a major modification in the way the package was used',
    title: 'Breaking changes',
    emoji: '💥',
    changelog: true,
    release: 'major',
    aliases: ['break'],
  },
  feat: {
    description: 'A new feature',
    title: 'Features',
    emoji: '✨',
    changelog: true,
    release: 'minor',
  },
  security: {
    description: 'A security update',
    title: 'Security',
    emoji: '🔒️',
    changelog: true,
    release: 'minor',
  },
  fix: {
    description: 'A bug fix',
    title: 'Bug Fixes',
    emoji: '🐛',
    changelog: true,
    release: 'patch',
  },
  perf: {
    description: 'A code change that improves performance',
    title: 'Performance Improvements',
    emoji: '⚡️',
    changelog: true,
    release: 'patch',
  },
  docs: {
    description: 'Documentation only changes',
    title: 'Documentation',
    emoji: '📝',
    changelog: true,
    release: false,
  },
  chore: {
    description: "Other changes that don't significantly modify the code",
    title: 'Chores',
    emoji: '🏗',
    changelog: true,
    release: false,
    aliases: ['chores', 'misc', 'other'],
  },
  refactor: {
    description: 'A code change that neither fixes a bug nor adds a feature',
    title: 'Code Refactoring',
    emoji: '♻️',
    changelog: true,
    release: 'patch',
  },
  test: {
    description: 'Adding missing tests or correcting existing tests',
    title: 'Tests',
    emoji: '🚦',
    changelog: true,
    release: false,
    aliases: ['tests'],
  },
  style: {
    description:
      'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)',
    title: 'Code Style and Formatting',
    emoji: '🎨',
    changelog: true,
    release: false,
    aliases: ['format', 'lint'],
  },
  build: {
    description:
      'Changes that affect the build system or external dependencies',
    title: 'Build',
    emoji: '👷',
    changelog: true,
    release: 'patch',
  },
  ci: {
    description: 'Changes to our CI configuration files and scripts',
    title: 'Continuous Integrations',
    emoji: '⚙️',
    changelog: true,
    release: false,
  },
  deps: {
    description: 'Update to our dependencies',
    title: 'Dependencies',
    emoji: '⚙️',
    changelog: true,
    release: 'patch',
    aliases: ['dev-deps'],
  },
  metadata: {
    description: 'Update to metadata of the project (e.g. package.json)',
    title: 'Metadata',
    emoji: '🗃️',
    changelog: true,
    release: 'patch',
  },
  revert: {
    description: 'Reverts a previous commit',
    title: 'Reverts',
    emoji: '⏪️',
    changelog: true,
    release: 'patch',
  },
  release: {
    description: 'Force the release of a new version',
    title: 'Release',
    emoji: '🔖',
    changelog: false,
    release: 'patch',
    aliases: ['bump'],
  },
  wip: {
    description: 'Code that is being worked on',
    title: 'Work In Progress',
    emoji: '🚧',
    changelog: true,
    release: false,
  },
}
