/* eslint-disable sort-keys, sort-keys/sort-keys-fix, perfectionist/sort-objects */

module.exports = {
  breaking: {
    aliases: ['break'],
    changelog: true,
    description:
      'A change breaking the backward compatibility and/or bringing a major modification in the way the package was used',
    emoji: '💥',
    release: 'major',
    title: 'Breaking changes',
  },
  feat: {
    changelog: true,
    description: 'A new feature',
    emoji: '✨',
    release: 'minor',
    title: 'Features',
  },
  security: {
    changelog: true,
    description: 'A security update',
    emoji: '🔒️',
    release: 'minor',
    title: 'Security',
  },
  fix: {
    changelog: true,
    description: 'A bug fix',
    emoji: '🐛',
    release: 'patch',
    title: 'Bug Fixes',
  },
  style: {
    aliases: ['ui', 'ux'],
    changelog: true,
    description:
      'Changes that only affect the visual identity of the product (fonts, color, spacing, ...)',
    emoji: '💄',
    release: 'minor',
    title: 'UI/UX',
  },
  performance: {
    aliases: ['perf'],
    changelog: true,
    description: 'A code change that improves performance',
    emoji: '⚡️',
    release: 'patch',
    title: 'Performance Improvements',
  },
  docs: {
    aliases: ['doc'],
    changelog: true,
    description: 'Documentation only changes',
    emoji: '📝',
    release: false,
    title: 'Documentation',
  },
  chores: {
    aliases: ['chore', 'misc', 'other'],
    changelog: true,
    description: "Other changes that don't significantly modify the code",
    emoji: '🏗',
    release: false,
    title: 'Chores',
  },
  refactor: {
    changelog: true,
    description: 'A code change that neither fixes a bug nor adds a feature',
    emoji: '♻️',
    release: 'patch',
    title: 'Code Refactoring',
  },
  tests: {
    aliases: ['test'],
    changelog: true,
    description: 'Adding missing tests or correcting existing tests',
    emoji: '🚦',
    release: false,
    title: 'Tests',
  },
  format: {
    aliases: ['lint'],
    changelog: true,
    description:
      'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, ...)',
    emoji: '🎨',
    release: false,
    title: 'Code Style and Formatting',
  },
  build: {
    changelog: true,
    description:
      'Changes that affect the build system or external dependencies',
    emoji: '👷',
    release: 'patch',
    title: 'Build',
  },
  ci: {
    changelog: true,
    description: 'Changes to our CI configuration files and scripts',
    emoji: '⚙️',
    release: 'patch',
    title: 'Continuous Integrations',
  },
  deps: {
    aliases: ['dev-deps'],
    changelog: true,
    description: 'Update to our dependencies',
    emoji: '📦',
    release: 'patch',
    title: 'Dependencies',
  },
  metadata: {
    aliases: ['meta'],
    changelog: true,
    description: 'Update to metadata of the project (e.g. package.json)',
    emoji: '🗃️',
    release: 'patch',
    title: 'Metadata',
  },
  revert: {
    changelog: true,
    description: 'Reverts a previous commit',
    emoji: '⏪️',
    release: 'patch',
    title: 'Reverts',
  },
  release: {
    aliases: ['bump'],
    changelog: false,
    description: 'Force the release of a new version',
    emoji: '🔖',
    release: 'patch',
    title: 'Release',
  },
  wip: {
    changelog: false,
    description: 'Code that is being worked on',
    emoji: '🚧',
    release: false,
    title: 'Work In Progress',
  },
}
