# This is a Github Workflow that runs lint, formatter and unit tests on every
# push and pull request.

# If everything pass and we are on the `main` branch, it also runs Semantic
# Release.

name: CI

on: [push, pull_request]

jobs:
  security:
    name: Check Yarn cache integrity
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - if: github.actor == 'snowball-tech-bot' || github.actor == 'renovate[bot]'
        name: Checking if user is a trusted bot
        run: |
          echo "User is a trusted bot user."
          echo "IS_BOT_USER=1" >> $GITHUB_ENV

      - if: env.IS_BOT_USER != 1
        uses: tspascoal/get-user-teams-membership@v2
        id: checkIsSnowballEngineeringTeamMember
        with:
          username: ${{ github.actor }}
          team: engineering
          GITHUB_TOKEN: ${{ secrets.MACHINE_GITHUB_TOKEN }}

      - if: env.IS_BOT_USER || steps.checkIsSnowballEngineeringTeamMember.outputs.isTeamMember == 'true'
        name: No need to check the cache integrity
        run: |
          echo "User is a member of the Snowball engineering team or a trusted bot user."
          echo "SKIP_INTEGRITY_CHECK=1" >> $GITHUB_ENV

      - if: env.SKIP_INTEGRITY_CHECK != 1
        uses: actions/checkout@v3

      - if: env.SKIP_INTEGRITY_CHECK != 1
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - if: env.SKIP_INTEGRITY_CHECK != 1
        name: Checking cache integrity
        run: yarn install --check-cache --immutable --immutable-cache


  quality:
    name: Checking code quality
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Installing dependencies
        run: yarn install --immutable --immutable-cache

      - name: Starting TurboRepo local cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Checking linter
        run: yarn turbo run lint

      - name: Checking format
        run: yarn turbo run format

  release:
    name: Release updated packages
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MACHINE_GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Installing dependencies
        run: yarn install --immutable --immutable-cache

      - name: Starting TurboRepo local cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Building all packages
        run: yarn turbo run build

      - name: Publishing updated packages to NPM, Git and GitHub
        env:
          GH_TOKEN: ${{ secrets.MACHINE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.MACHINE_NPM_TOKEN }}
          GIT_AUTHOR_NAME: '@snowball-tech-bot'
          GIT_AUTHOR_EMAIL: snowball-bot@snowball.xyz
          GIT_COMMITTER_NAME: '@snowball-tech-bot'
          GIT_COMMITTER_EMAIL: snowball-bot@snowball.xyz
        run: yarn publish:all
