# This is a Github Workflow that runs lint, formatter and unit tests on every
# push and pull request.

name: Quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality:
    name: Checking code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 22.x

      - name: Setting up dependencies & workspaces
        run: yarn install --immutable --immutable-cache && yarn run -T setup

      - name: Checking linter
        run: yarn run -T lint

      - name: Checking format
        run: yarn run -T format

      - name: Checking typings
        run: yarn run -T types-check
