# This is a Github Workflow that runs lint, formatter and unit tests on every
# push and pull request.

name: Quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Checking code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Installing dependencies
        run: yarn install --immutable --immutable-cache

      - name: Setting up each workspace
        run: yarn workspaces foreach -p run setup

      - name: Checking linter
        run: yarn run -T lint

      - name: Checking format
        run: yarn run -T format
