# This is a Github Workflow that waits for quality and security to be executed
# on the `main` branch.

# If everything pass it also release all package using Semantic Release.

name: Release

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

permissions:
  # For checkout.
  contents: read

jobs:
  release:
    name: Releasing updated packages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      # For publishing a GitHub release.
      contents: write
      # To be able to comment on released issues.
      issues: write
      # To be able to comment on released pull requests.
      pull-requests: write
      # To enable use of OIDC for trusted publishing and npm provenance.
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.MACHINE_GITHUB_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: yarn

      - name: Setting up dependencies & workspaces
        run: yarn install --immutable && yarn run -T setup

      - name: Building all packages
        run: yarn run -T build

      - name: Waiting for quality to pass
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.ref }}
          check-name: Checking code quality
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Publishing updated public packages to NPM, Git & GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.MACHINE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: '@snowball-tech-bot'
          GIT_AUTHOR_EMAIL: snowball-bot@snowball.xyz
          GIT_COMMITTER_NAME: '@snowball-tech-bot'
          GIT_COMMITTER_EMAIL: snowball-bot@snowball.xyz
        run: yarn run -T publish-all
